### PR TITLE
Fix bug to allow creating documents in nested collections

### LINKED ISSUE #12: Unable to create documents in nested collections
Running this:

```rs
let mut client: FirestoreClient = self.database().await;

client
    .create_document_at_ref(
        &collection("users")
            .doc(user_id.to_string())
            .collection("requestedCampaigns")
            .doc(campaign_id.to_string()),
        &campaign_request,
    )
    .await?;
```

produces the following error:

```bunyan
Caused by:
    status: InvalidArgument, message: "Collection id \"users/01GF16QNKRH1J4KJX101A33FA6/requestedCampaigns\" is invalid because it contains \"/\".", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Thu, 13 Oct 2022 13:34:29 GMT", "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\""} }
```

### PR DESCRIPTION
**Pull request by avborup**
Closes #12.

### CODE REVIEW

File: tests/create_document.rs [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+
+    let doc = client
+        .get_document::<serde_json::Value>(&doc_ref)
+        .await?
+        .unwrap();
+
+    assert_eq!(doc["title"], "Alice in Wonderland");
+    assert_eq!(doc["author"], "Lewis Carroll");
+
+    Ok(())
```
Comment (JoachimBorup) [inline tests/create_document.rs:30]: Cool. I assume this and the return type lets you propagate errors for better error messages?

**Review by JoachimBorup — APPROVED** [review]
